server:
  port: 8084

spring:
  application:
    name: api-gateway

  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/api/**

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    server:
      waitTimeInMsWhenSyncEmpty: 0